ethereum:
  - name: Uniswap v3
    type: uniswap_v3
    addresses:
      pool: "0xC2e9F25Be6257c210d7Adf0D4Cd6E3E881ba25f8"
      router: "0xE592427A0AEce92De3Edee1F18E0157C05861564"
      quoter_v2: "0x61fFE014bA17989E743c5F6cB21bF9697530B21e"
    pairs:
      - token0: WETH9
        token1: DAI
      - token0: WETH9
        token1: WBTC
      - token0: WETH9
        token1: USDC
  - name: Uniswap v2
    type: uniswap_v2
    addresses:
      factory: "0x5C69bEe701ef814a2B6a3EDD4B1652CB9cc5aA6f"
      router: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D"
    meta:
      fee:
        numerator: 3
        denumerator: 100
    pairs:
      - token0: WETH9
        token1: DAI
      - token0: WETH9
        token1: WBTC
      - token0: WETH9
        token1: USDC
  - name: PancakeSwap
    type: uniswap_v2
    addresses:
      factory: "0x1097053Fd2ea711dad45caCcc45EfF7548fCB362"
      router: "0xEfF92A263d31888d860bD50809A8D171709b7b1c"
    meta:
      fee:
        numerator: 25
        denumerator: 1000
    pairs:
      - token0: WETH9
        token1: USDC
  - name: SushiSwap
    type: uniswap_v2
    addresses:
      factory: "0xC0AEe478e3658e2610c5F7A4A2E1777cE9e4f2Ac"
      router: "0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F"
    meta:
      fee:
        numerator: 3
        denumerator: 100
    pairs:
      - token0: WETH9
        token1: DAI
      - token0: WETH9
        token1: WBTC
      - token0: WETH9
        token1: USDC
gnosis:
  # - name: Empire
  #   type: uniswap_v2
  #   addresses:
  #     factory: "0x06530550A48F990360DFD642d2132354A144F31d"
  #     router: "0xe5759714998e8B50A33c7333C04C2d02e5dcE77f"
  #   meta:
  #     fee:
  #       numerator: 3
  #       denumerator: 100
  #   pairs:
  #     - token0: WXDAI
  #       token1: GNO
  #     - token0: WXDAI
  #       token1: USDC
  #     - token0: WXDAI
  #       token1: WBTC
  - name: HoneySwap
    type: uniswap_v2
    addresses:
      factory: "0xA818b4F111Ccac7AA31D0BCc0806d64F2E0737D7"
      router: "0x1C232F01118CB8B424793ae03F870aa7D0ac7f77"
    meta:
      fee:
        numerator: 3
        denumerator: 100
    pairs:
      - token0: WXDAI
        token1: GNO
      - token0: WXDAI
        token1: WETH9
      - token0: WXDAI
        token1: USDC
      - token0: WXDAI
        token1: WBTC
  - name: SushiSwap
    type: uniswap_v2
    addresses:
      factory: "0xc35DADB65012eC5796536bD9864eD8773aBc74C4"
      router: "0x1b02dA8Cb0d097eB8D57A175b88c7D8b47997506"
    meta:
      fee:
        numerator: 3
        denumerator: 100
    pairs:
      - token0: WXDAI
        token1: GNO
      - token0: WXDAI
        token1: WETH9
      - token0: WXDAI
        token1: USDC
      - token0: WXDAI
        token1: WBTC
  - name: Swapr
    type: uniswap_v2
    addresses:
      factory: "0x5D48C95AdfFD4B40c1AAADc4e08fc44117E02179"
      router: "0xE43e60736b1cb4a75ad25240E2f9a62Bff65c0C0"
    meta:
      fee:
        numerator: 25
        denumerator: 1000
    pairs:
      - token0: WXDAI
        token1: GNO
      - token0: WXDAI
        token1: WETH9
      - token0: WXDAI
        token1: USDC
      - token0: WXDAI
        token1: WBTC
